name: entitlementForSlack
description: CloudAz for Slack Application
version: 0.2.0
author: thomas.hii@nextlabs.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.2
  angular_router: ^2.0.0
  skawa_material_components: ^1.5.0
  angular_forms: ^3.0.0
  firebase: ^7.2.1
  uuid: ^2.0.4
dependency_overrides:
  dart_internal: ^0.2.0

dev_dependencies:
  angular_test: ^3.0.0
  build_runner: ^1.10.6
  build_test: ^1.3.0
#  build_web_compilers: ^2.13.0
  build_web_compilers: ^2.12.2
  test: ^1.15.5
  sass_builder: ^2.1.3

